apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f92iuyxzy-nodejs
  janus-idp.io/tekton: f92iuyxzy-nodejs
  backstage.io/kubernetes-id: f92iuyxzy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f92iuyxzy-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
