apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f92iuyxzy-nodejs 
  janus-idp.io/tekton: f92iuyxzy-nodejs
  backstage.io/kubernetes-id: f92iuyxzy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f92iuyxzy-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  